# 산포통계

In [16]:
import numpy as np
from scipy import stats
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

## 분산 계산

In [2]:
x = [1, 2, 3, 4, 5]
print(np.var(x, ddof = 1))
print(np.array(x).var())
print(pd.Series(x).var(ddof = 0))

2.5
2.0
2.0

## 표준편차 계산

In [3]:
x = [1, 2, 3, 4, 5]
print(np.std(x, ddof = 1))
print(np.array(x).std(ddof = 0))
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898

## 변동계수의 필요성

In [4]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1, ddof = 1))
print(np.std(x2, ddof = 1))

1.5811388300841898
15.811388300841896

In [5]:
print(stats.variation(x1))
print(stats.variation(x2))

0.47140452079103173
0.4714045207910317

In [6]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

0.5270462766947299
0.5270462766947299

## 스케일링

In [7]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

In [8]:
# standard scaling

z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [9]:
# Min-max scaling

z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

In [14]:
X = pd.DataFrame(
    {"x1":[1, 2, 3, 4, 5],
    "x2": [10, 20, 30, 40, 50]}
    )

X

   x1  x2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [17]:
scaler = MinMaxScaler()
z = scaler.fit_transform(X)
pd.DataFrame(z, columns=['x1', 'x2'])

     x1    x2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [19]:
ss_scaler = StandardScaler()
s = ss_scaler.fit_transform(X)
pd.DataFrame(s, columns=['x1', 'x2'])

         x1        x2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

## 범위와 사분위 범위 계산

In [20]:
# np.random.normal(평균, 편차, size = 갯수)

x = np.random.normal(100, 20, size = 1000)
x

array([ 52.73904721,  92.46581377,  93.68802953,  61.30774379,
        99.57352737, 107.48026843, 105.30859962, 121.78567927,
       117.57519533,  76.12831197, 134.26491489,  51.46455215,
        97.82399436, 110.85134777,  96.30900214, 117.15918762,
       105.10435777,  89.85651527,  71.17960667,  81.3006357 ,
        97.6182541 ,  88.47815204, 119.04891128, 127.02144833,
        76.82590788,  87.76350792,  96.75922665,  92.417873  ,
        93.67964516, 111.43822695,  78.84323281,  85.16526722,
       103.6608268 ,  89.36552551, 103.69360037,  96.99247556,
       132.28618847,  99.18571793,  89.70834327, 103.69580862,
        97.76771188, 115.57052455, 127.09557892,  99.91051843,
        93.92680155,  98.29789086,  72.96852826,  98.63564913,
       118.05298004,  65.21447555, 124.25687342, 114.78375484,
       114.52500287,  70.38658575,  81.84594111,  95.85858916,
        79.55779188,  68.57514091, 112.1836658 , 133.64085168,
       126.7846973 ,  86.17027575, 109.46502043, 113.3320243 ,
        96.66271958, 132.65578116,  83.83965524,  81.8641991 ,
       107.63189271,  73.54700587,  94.91118365,  96.50905235,
        97.64354405, 106.8098479 , 116.05992232,  92.61437397,
        96.7879034 ,  98.63161238,  85.30362827,  92.9156733 ,
        74.59862159, 116.18420723, 110.48086214, 125.37280126,
        83.24729014, 117.85904161, 130.61044895,  83.25626238,
       101.23104897, 135.17753611,  73.53270718, 103.94172894,
       134.29509505,  82.77229424, 108.71566737,  87.89604133,
       122.27013003, 105.99593245, 141.20484283, 134.31444271,
       113.81296962,  88.97483231,  83.52882583,  68.81838064,
        68.94649858, 103.67883262, 107.55365632, 119.10629128,
        86.38752723,  79.20459813,  98.86180556,  92.48723708,
        89.91964769,  92.05956838,  87.37740727, 100.91525011,
       116.41458243, 109.10053254, 102.03342793, 103.79068369,
        93.70488227, 107.3629746 , 102.86958075, 105.69665507,
       123.88794202, 110.22168421, 104.88604017, 106.39367797,
        83.96513363,  99.80710621, 130.43517989,  95.67653342,
       117.56101908, 128.28290424, 117.39740708, 106.57669895,
       117.8125064 ,  70.08441984, 131.67654494, 109.68800944,
        72.21723452, 120.04198848,  87.51866707,  90.49214211,
        83.26683971, 105.15792338, 123.59089241,  89.95395903,
        73.10715315,  85.04381384,  83.04103233,  81.59503152,
        93.91696018,  97.42885754, 119.03820539, 110.99005567,
       128.74545758,  96.45762371,  83.68805634,  98.53323735,
       122.35870726, 110.09147564, 105.77979303, 120.84536145,
       142.13324835,  59.24453275,  93.18315893,  68.80465597,
        94.23316373,  85.79164628,  97.80832555, 103.59823865,
       117.28618058,  85.99826513, 139.35344449,  89.54354959,
        75.04384297,  93.07263703, 127.37153959, 124.05362641,
       130.4481457 , 105.5989792 ,  99.34616562,  58.63965011,
       104.17962868,  79.61494919,  92.35815406, 112.75665062,
        96.51785212, 127.92429277,  62.93366059, 118.28411116,
       105.5824431 , 109.09180558,  71.76367408,  64.16647027,
       108.10445713, 110.38437106, 101.97022339,  98.55588197,
       145.75264015, 139.93565601,  96.0152926 ,  89.73186179,
       121.16355171,  49.34154268, 128.63661839,  52.23737068,
        88.67222491, 102.90625096, 114.00569268, 106.06962827,
       119.07580208,  92.2457726 , 127.70195104,  69.65558267,
        97.24959628,  81.569979  ,  97.5782509 ,  90.53859823,
       122.01816519, 101.17824275, 119.086018  , 133.19494001,
       112.55811828,  81.05266833, 110.1699324 ,  93.76306246,
       105.20364206, 105.12548053, 108.65056699,  84.07384833,
        93.37539164,  93.07593354, 121.45097241, 135.64119363,
        78.87882581, 114.95437158,  85.97447237,  92.36783236,
       116.15088719, 110.37416708,  75.23324253, 104.39914949,
        55.90590185, 113.25498331,  97.34447306,  91.62896585,
       119.90333931,  93.10338826, 125.74189401, 120.73121898,
        96.61022075,  85.58481664, 131.2422752 , 124.99398601,
        98.12018162,  95.07536276, 100.19884158,  84.07411748,
       102.37594244,  87.17120883, 136.01702964,  61.76185225,
        96.76176616, 119.3588702 , 105.29205036, 129.28645503,
       124.09059713, 114.35251374,  79.00424859,  67.63127824,
       133.0754017 ,  68.60884405,  60.79012505, 104.50700719,
        79.04433159, 115.33253547,  95.92008838, 119.51615198,
       108.66916815,  57.63062593, 129.63310229, 107.27569586,
       131.59210874, 107.89727976, 114.43796692, 124.45102774,
        73.4914022 ,  93.84641865, 117.18651826, 108.28234085,
        87.75080393,  72.74732392, 130.93758229,  76.78040828,
       103.29796754, 105.63734625,  56.8112373 ,  95.38168456,
        91.67700899,  92.71713498, 120.05872034,  93.24512717,
       105.90029172,  98.81562768, 114.43483921, 135.37410196,
       120.57607093,  70.31718786, 114.92454241,  77.61123916,
       105.33473378,  68.67682684, 103.18526595, 102.94242421,
        61.52147045,  79.41746936, 120.24808261,  75.52911521,
       123.95508132, 120.55165265, 108.44850649, 126.39383069,
       109.39225169,  75.78917687,  87.17604733,  76.29613461,
        89.66149501,  82.67742221, 105.42490648,  90.11589897,
        94.87103631, 120.66519018,  90.51531602,  70.02596119,
       108.40357579, 126.35501827,  94.64214487,  93.67544342,
       105.51874369, 102.74760628, 130.14403568, 104.13126832,
       151.32774368,  91.96555719,  90.76257953, 110.39190442,
       128.41688398,  92.39703653, 126.84241286, 131.36207989,
        71.84532056, 113.57748405,  94.13365295, 110.00811529,
       105.02903972,  82.82282247, 126.05125859,  78.47986027,
       109.40715255, 107.17213752,  72.38815718,  91.06636815,
        89.13492423,  87.74363107,  86.91065501,  88.23690897,
        79.57015528, 126.47228409,  63.56033182, 116.58153869,
       117.04124349, 122.1282789 ,  85.06677147,  50.10755307,
       104.98139071,  70.04771266,  83.38700248,  60.96399996,
        85.36644299,  89.64266563,  91.01755933,  86.83680767,
        94.54084191, 112.78372417,  97.05336359, 104.07347287,
        89.88257136,  69.35008485,  86.48135085,  81.1191748 ,
        73.95055072, 110.63370882, 103.00555793,  89.06529137,
        97.2506992 ,  99.67520474, 119.50304619,  79.8344521 ,
       107.29640444,  93.9278476 , 121.9555527 , 140.87730817,
        88.23862176, 112.09871564,  83.78769626,  94.28094179,
       106.95961619, 129.47738357,  69.988878  , 103.19141173,
        76.13461415, 113.48731742, 110.55473885,  90.58369168,
       117.97679175,  74.4467635 ,  75.78448594, 109.29539585,
        87.39704248,  96.99259821, 115.50191885, 110.78228552,
        74.12328737,  90.32075333,  90.21313379, 108.47574359,
        39.91831235,  77.44118421, 125.74102507, 107.13350458,
        97.62210319,  73.27925068, 106.2195656 ,  92.34952364,
        71.04107814,  95.28145663, 118.51404868,  64.31612206,
       115.74393919,  86.20261116,  86.32068074,  47.91467951,
       123.40639356, 117.77505569, 115.04937029,  83.24987767,
        96.48725002,  89.25754975,  81.20135587,  84.61330671,
       106.5629186 , 110.83256223,  81.03525209, 118.20454382,
       122.56824668,  67.16144218, 143.87094989, 116.5698669 ,
       109.50411298, 101.45428454, 116.35932126,  67.59024093,
        80.74274136, 122.85754513,  93.56536467,  99.48300166,
       142.56380975,  73.07432266,  88.82274622,  84.95719381,
       111.55143286, 119.60289399,  94.02347788,  80.40510797,
       141.54053326, 141.46288327,  81.76784841,  94.56320938,
        93.88581463,  95.10871779,  94.27613415,  79.42604777,
       121.48246376,  81.66339216,  82.5122115 ,  80.10112058,
       104.3665428 ,  67.21023901,  95.94986405,  75.47370616,
        93.36852162,  54.5581724 , 146.85978514,  99.63311186,
       135.70528219, 112.2912542 , 114.90282563, 102.197674  ,
        87.69818072,  91.84489012,  90.35214686, 105.04503878,
       104.5055208 , 102.86568538, 109.10504774,  93.74943659,
        86.81224868, 100.06237506, 107.29185947,  90.48437172,
        90.29439648,  84.79423078,  90.97990206, 111.6113066 ,
        81.5268473 , 107.80411002,  88.49726151, 102.10518147,
       103.51279136,  85.51667943,  80.01586852,  99.90660416,
        90.3823797 , 122.19128438,  93.23348393, 102.42514293,
        98.23449778,  88.16383573,  72.04664822, 114.31859995,
       103.44068134,  94.74012674, 127.31590366,  88.38090884,
        72.68941065, 103.45587328,  88.63121458,  74.90601309,
        83.924172  , 110.2515191 , 117.65637725, 102.07521294,
        81.96063806, 124.66352027,  84.40491097, 107.65225987,
       120.71072299, 131.25116968,  92.37243913, 129.65882032,
       133.31176612, 103.62757786,  89.66018134,  68.12872965,
        60.5633707 ,  91.77618856, 105.82143473, 109.12517177,
       131.5787641 , 107.99914436, 107.14634425,  91.78314838,
       143.29945292, 103.19569495,  93.410228  , 148.05231768,
       109.43102413,  43.12437113,  95.74665232, 128.37991602,
       147.99957215, 102.54343669, 131.99614246,  77.32570882,
       106.79087983, 104.87882242, 134.07853475,  80.44656118,
        97.81693665,  98.5497476 , 119.69189942, 104.2899254 ,
       119.79058187, 120.19541796,  68.2061259 ,  99.60887333,
       107.88397146, 100.83104592, 102.84544675,  77.15987241,
        99.50004237, 102.38821713,  86.08341068,  91.76629525,
        89.84703651, 100.31218817, 116.28658184, 144.28506473,
       109.86001079, 117.10807806, 109.1505792 , 128.57133127,
       101.37555768,  92.20040039,  77.61854017, 124.39256352,
       111.45854866, 126.8397199 , 137.49867993,  94.95811215,
        72.1560828 ,  99.10617393,  82.43567331, 115.27232959,
        99.70471117, 153.9461813 , 125.88573912, 131.9370268 ,
        85.77059092, 107.37821338,  97.43934732, 121.02793236,
       123.23857007, 104.53470248,  98.32195938,  79.3676831 ,
        96.94987813,  87.47447334, 118.12742078,  64.11121163,
       103.59806185, 150.70365773,  93.41527972,  84.11320062,
       126.78996522,  71.6731886 ,  83.19787546, 102.90209465,
        87.09895261,  81.02911648, 100.6282567 ,  90.6990133 ,
        96.98105667, 105.28107632, 131.83023411,  96.8284972 ,
        71.09161694, 120.03416432,  99.19599223, 138.42263641,
       115.11538196,  87.79202374, 149.81173274, 139.43263953,
        81.77560988,  75.58971153, 109.53780486, 104.61601   ,
       106.94069136, 124.92149949, 146.13597962,  78.4400402 ,
        96.44013607, 109.27507335, 141.60872049,  88.2882723 ,
        91.03664483,  88.75272369,  63.75032775,  91.09777614,
       131.41363833, 129.98681079,  89.06672906, 123.60916864,
        92.39894481,  95.9749362 , 101.39002574, 101.5272653 ,
       113.90641015, 144.9820718 , 109.46641624, 121.0730553 ,
        93.88777154, 108.06335365,  79.28600361,  91.069807  ,
        82.01778849, 108.04183465,  78.93536961, 105.65699406,
       105.86537334,  96.77877305,  79.72244956,  92.28582979,
       106.54229769,  97.32376197,  87.25389605,  65.7937839 ,
       130.73758859,  74.85546464,  67.51360396,  99.04732579,
        93.81510861,  99.64699677, 105.04570343,  83.89739504,
        72.38227254,  55.31651309,  99.75418075, 127.20600692,
       111.36395023, 107.65388397, 124.38630248, 114.31162706,
        87.62029949, 145.10401509,  78.22913841, 108.75145545,
       124.69803537, 108.55703832,  95.27638889,  65.37893013,
       126.94919945, 108.87184528, 141.93419021, 102.25951726,
        96.33668666, 118.83076338,  90.25552187, 131.10883441,
        69.72922425, 121.86762011,  92.90189896, 112.22001309,
        91.13008881, 103.25458781, 124.56599544, 123.6094426 ,
       133.72110566, 119.89755426,  97.64013925, 110.75092028,
        73.71881176,  96.95127587,  74.56377979, 116.8976154 ,
       129.33843527,  79.52475472,  81.16513283,  93.24536636,
       123.86562664, 128.62274846,  96.2897208 ,  98.78270945,
        92.99426129,  96.9386436 ,  77.52648277,  93.30355104,
        97.30812441,  61.56600648, 116.95826637, 107.47591003,
        84.67487106, 122.40175538,  76.4167178 ,  65.89476182,
        65.47568502, 105.12426879, 115.47721927,  88.29603199,
       109.043397  , 101.9762506 , 106.3494349 ,  96.77484377,
        92.16339301, 126.44550326, 128.58477196, 109.80466121,
       120.85961291,  91.9763665 ,  89.23652508, 108.07491172,
        86.07681276,  84.31423334,  69.77057573, 118.83952985,
        75.07610316,  94.49847443,  85.15826466,  76.31512356,
        97.31434774,  98.8685624 , 110.86118222,  89.54237349,
       118.82450763, 100.35234489,  86.98583592,  96.24961419,
        67.19714009, 128.46525069, 109.88662781,  53.25217455,
        49.31687644, 107.1123316 ,  91.81453852,  70.49687841,
       124.24837406,  93.02313056,  65.04409096, 111.57434276,
        91.98619445,  92.95768887,  74.85959615, 102.6099952 ,
        66.27086269, 102.79966093,  76.32957655,  92.29052973,
        78.21310535, 100.0923343 ,  99.18304966, 112.68561908,
        66.02924307,  92.06332051,  83.72283282,  93.83994426,
       122.32795528,  97.76245654, 129.58923146,  54.16873933,
        67.42968294,  79.56587903, 123.12833308, 118.03707689,
       103.48482919,  97.05813192, 129.71061059,  84.13803451,
        98.39936106,  87.47210581, 117.79800844,  71.18131008,
        85.52490498, 108.95899727, 108.45926436,  98.77906597,
        85.02803094,  94.96362959, 107.35760741, 131.02212113,
        95.61013849,  71.18093096,  82.42107834,  82.35632348,
        83.19663094, 107.67202358,  72.26529305, 116.43099372,
        90.11194412,  95.76384378,  82.98179814,  99.19669191,
        83.75444455,  95.24993416,  76.26554455,  69.06578969,
        97.34247067,  80.8328874 , 109.10930944, 108.25971307,
       102.26287583, 114.75311012,  77.74592477, 113.04890868,
        86.17888815, 112.74971358,  98.97192488, 123.20797125,
       107.66040789,  62.26550258, 133.69760309,  73.23799645,
       105.97914615, 121.03677006,  67.4966431 , 100.74602045,
        99.97743422,  75.37981557,  78.23382328, 115.86723439,
       109.17159822, 140.02128771,  59.5668769 ,  87.11379149,
        91.60673285, 107.55245907,  86.00428659,  78.68620826,
       117.52344688,  92.33928544,  84.94654884, 113.29813547,
        85.41761013, 123.99011065,  89.2023944 ,  93.11064181,
       118.320449  ,  74.10925631,  97.74557652, 127.64213936,
        91.89671478, 145.41531883, 103.39714372, 101.24848246,
        75.86664133, 132.36172687, 104.77627545, 101.5998815 ,
       122.16499526,  85.77757545, 100.10598249, 102.6638891 ,
       120.68625103,  54.91624809, 100.94800535,  58.60394769,
        98.91454829,  88.99778753,  81.98696036,  76.69487908,
        93.61998849,  98.70586831, 103.82397319,  91.99855577,
       133.09654468,  46.39422614,  60.92171497,  89.07323578,
        87.20338856, 121.07832024,  77.8755457 ,  92.56860629,
        93.98476943,  91.13529956,  95.42718668, 119.73240019,
        85.34277159, 114.90038357,  74.87013343, 104.07350004,
        60.38065176,  82.25128516,  71.53363074, 105.55530809,
        88.06509082,  78.39132779, 124.38334135,  97.12066267,
        82.97421453, 115.84194017,  80.78037146, 104.31730352,
        99.61327615,  94.32298248,  60.69431308, 136.99932327,
        86.35715751, 102.09758278,  43.87822292, 107.69764881,
        85.80604019,  89.98312498,  92.1144595 ,  81.85130555,
       103.81496895, 137.38100454,  86.47542093,  73.89641818,
        64.31203878, 142.15987974, 120.03375472,  80.60936001,
        91.64250955, 124.50527315, 113.2266647 , 124.92148224,
        97.91222081,  79.63474889,  99.97012982, 106.96354971,
       110.13601062, 129.16901929, 140.85801961, 134.45261064,
        77.22990936,  90.20075186,  77.02861923, 111.63166599])

In [21]:
print(np.ptp(x))
print(np.max(x) - np.min(x))

114.0278689548434
114.0278689548434

In [22]:
print(np.quantile(x, 0.75) - np.quantile(x, 0.25))
print(stats.iqr(x))

27.333407026072337
27.333407026072337